# pyproject.toml for csv-beans

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "csv-beans"
version = "0.0.2"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11.2"
dependencies = ["csv-app>=0.0.2", "tui-app>=0.0.2"]

[project.optional-dependencies]
test = [
    "pytest>=9.0.3",
    "pytest-mock>=3.15.1",
]

[project.urls]
repository = "https://github.com/dangyogi/csv-beans.git"

[project.scripts]
beans-rows = "csv_beans.rows:run"
beans-tables = "csv_beans.tables:run"
#cash-balance = "csv_beans.cash_balance:run"
#cash-swap = "csv_beans.cash_swap:run"
#set-end-date = "csv_beans.set_end_date:run"
#treasurer-report = "csv_beans.treasurer_report:run"
#update-reconcile = "csv_beans.update_reconcile:run"
beans = "csv_beans.tui:run"

[tool.setuptools.package-dir]
csv_beans = "csv_beans"

[tool.pytest.ini_options]
testpaths = ["tests"]
